fix(types): import TextMeshImpl does not have a type definition
`TextMeshImpl` does not have a type definition so the declaration files fail to type-check with this error:

```
node_modules/@react-three/drei/core/Text.d.ts:49:24 - error TS2304: Cannot find name 'TextMeshImpl'.

49     onSync?: ((troika: TextMeshImpl) => void) | undefined;

```