fix: type error in Example.tsx
Found I was having this type error in my node_modules when running type check in my project.

This looks to be due to an incorrect syntax when importing this type, although I might be unaware of a newer TS feature.

```
node_modules/@react-three/drei/core/Example.d.ts:2:15 - error TS1005: ',' expected.

2 import { type Color } from '@react-three/fiber';
```